// Generated by CoffeeScript 1.4.0
(function() {
  var calcTimingFunctionsDemo;

  $(document).ready(function() {
    calcTimingFunctionsDemo();
    return $(window).resize(function() {
      return calcTimingFunctionsDemo();
    });
  });

  calcTimingFunctionsDemo = function() {
    var code_width, demo_width, styles, t_el, transition_space;
    t_el = $('#timing-functions');
    demo_width = t_el.find('li').outerWidth();
    code_width = t_el.find('code').outerWidth();
    transition_space = demo_width - code_width + 60 + "px";
    styles = "<style media=\"screen\" type=\"text/css\" data-role=\"generated-demo\">\n  .main-content article#timing-functions section.demo:hover div.box {\n    -webkit-transform: translateX(" + transition_space + ");\n       -moz-transform: translateX(" + transition_space + ");\n        -ms-transform: translateX(" + transition_space + ");\n         -o-transform: translateX(" + transition_space + ");\n            transform: translateX(" + transition_space + ");\n  }\n</style>";
    $("[data-role='generated-demo']").remove();
    return $('head').append(styles);
  };

}).call(this);
